### ISSUE TITLE
我的设置好后不会自动重启！

### ISSUE THREAD

**Issue by zhongqiujie13** [peng4740/ibm-cf-restart-actions#10]
第一次运行以及手动运行都没有问题，但是不会自动运行！不晓得什么原因？

![IMG_20200831_131812.jpg](https://user-images.githubusercontent.com/16622626/91685469-fe24e100-eb8c-11ea-9eab-3b68e5610c6b.jpg)

**Comment by peng4740** [comment]
这已经运行完成了，你可以点进去看

**Comment by zhongqiujie13** [comment]
> 这已经运行完成了，你可以点进去看

不是应该每次重启完和你这个一样有个新的记录吗？我的这个就是三天前这一个运行记录

**Comment by peng4740** [comment]
可以尝试随意修改README.md文件后试试能不能正常工作
