### ISSUE TITLE
Unable to determine Go version to install: no match found for 1.11.x in [1.13.11 1.13.12 1.14.2 1.14.4]

### ISSUE THREAD

**Issue by dogeloveskitty** [peng4740/ibm-cf-restart-actions#9]
<img width="1092" alt="截屏2020-08-30 上午11 51 11" src="https://user-images.githubusercontent.com/50580645/91650172-3d80fe00-eab7-11ea-9865-96721ede3c76.png">
提示这种安装错误 应该怎么办呀

**Comment by peng4740** [comment]
看起来像是这个APP的问题，你在网页上手动重启这个APP能让它运行起来吗？
